// Generated by CoffeeScript 1.8.0
(function() {
  var diceRoller, sum;

  sum = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].reduce((function(t, n) {
    return t + n;
  }), 0);

  console.log(sum);

  diceRoller = require("../src/index");

  describe("existance", function() {
    it("should exist", function() {
      return (expect(diceRoller)).not.toBeUndefined();
    });
    it("should have a rollDice method ", function() {
      var rollDiceType;
      (expect(diceRoller.rollDice)).not.toBeUndefined();
      rollDiceType = typeof diceRoller.rollDice;
      return (expect(rollDiceType)).toBe("function");
    });
    it("should have a rollDice method and should be able to roll a die", function() {
      var spy;
      spy = spyOn(Math, "random");
      spy.andReturn(0.5);
      (expect(diceRoller.rollDice())).toBe(4);
      (expect(diceRoller.rollDice(10))).toBe(6);
      (expect(diceRoller.rollDice(10, 3))).toBe(18);
      (expect(diceRoller.rollDice(100))).toBe(51);
      spy.andReturn(0.99999);
      (expect(diceRoller.rollDice(2))).toBe(2);
      (expect(diceRoller.rollDice(4))).toBe(4);
      (expect(diceRoller.rollDice(6))).toBe(6);
      (expect(diceRoller.rollDice(10))).toBe(10);
      (expect(diceRoller.rollDice(18))).toBe(18);
      (expect(diceRoller.rollDice(20))).toBe(20);
      return (expect(diceRoller.rollDice(100))).toBe(100);
    });
    it("should have a rollList method ", function() {
      var rollListType;
      (expect(diceRoller.rollList)).not.toBeUndefined();
      rollListType = typeof diceRoller.rollList;
      return (expect(rollListType)).toBe("function");
    });
    it("should have a an array of rolled items", function() {
      var spy;
      spy = spyOn(Math, "random");
      spy.andReturn(0.5);
      (expect(diceRoller.rollList(6, 4))).toEqual([4, 4, 4, 4]);
      return (expect(diceRoller.rollList(10, 2))).toEqual([6, 6]);
    });
    it("should return 4 when random returns 0.5", function() {
      (spyOn(Math, 'random')).andReturn(0.5);
      return (expect(diceRoller.d6())).toBe(4);
    });
    return it("should have a function d6() which should roll between 0 and 7", function() {
      (expect(diceRoller.d6)).not.toBeUndefined();
      (expect(diceRoller.d6())).toBeGreaterThan(0);
      return (expect(diceRoller.d6())).toBeLessThan(7);
    });
  });

}).call(this);

//# sourceMappingURL=diceRollerSpec.js.map
