// Generated by CoffeeScript 1.8.0
(function() {
  var DiceRoller;

  DiceRoller = (function() {
    function DiceRoller() {}

    DiceRoller.prototype.rollDice = function(sides, numberOfDice) {
      var roll;
      if (sides == null) {
        sides = 6;
      }
      if (numberOfDice == null) {
        numberOfDice = 1;
      }
      roll = Math.floor((Math.random() * sides) + 1);
      if (numberOfDice === 1) {
        return roll;
      }
      return roll + this.rollDice(sides, numberOfDice - 1);
    };

    DiceRoller.prototype.d2 = function(numberOfDice) {
      if (numberOfDice == null) {
        numberOfDice = 1;
      }
      return this.rollDice(2, numberOfDice);
    };

    DiceRoller.prototype.d4 = function(numberOfDice) {
      if (numberOfDice == null) {
        numberOfDice = 1;
      }
      return this.rollDice(4, numberOfDice);
    };

    DiceRoller.prototype.d6 = function(numberOfDice) {
      if (numberOfDice == null) {
        numberOfDice = 1;
      }
      return this.rollDice(6, numberOfDice);
    };

    DiceRoller.prototype.d8 = function(numberOfDice) {
      if (numberOfDice == null) {
        numberOfDice = 1;
      }
      return this.rollDice(8, numberOfDice);
    };

    DiceRoller.prototype.d10 = function(numberOfDice) {
      if (numberOfDice == null) {
        numberOfDice = 1;
      }
      return this.rollDice(10, numberOfDice);
    };

    DiceRoller.prototype.d12 = function(numberOfDice) {
      if (numberOfDice == null) {
        numberOfDice = 1;
      }
      return this.rollDice(12, numberOfDice);
    };

    DiceRoller.prototype.d18 = function(numberOfDice) {
      if (numberOfDice == null) {
        numberOfDice = 1;
      }
      return this.rollDice(18, numberOfDice);
    };

    DiceRoller.prototype.d20 = function(numberOfDice) {
      if (numberOfDice == null) {
        numberOfDice = 1;
      }
      return this.rollDice(20, numberOfDice);
    };

    DiceRoller.prototype.d100 = function(numberOfDice) {
      if (numberOfDice == null) {
        numberOfDice = 1;
      }
      return this.rollDice(100, numberOfDice);
    };

    DiceRoller.prototype.rollList = function(sides, numberOfDice, list) {
      if (sides == null) {
        sides = 6;
      }
      if (numberOfDice == null) {
        numberOfDice = 1;
      }
      if (list == null) {
        list = [];
      }
      list.push(this.rollDice(sides));
      if (numberOfDice === 1) {
        return list;
      }
      return this.rollList(sides, numberOfDice - 1, list);
    };

    return DiceRoller;

  })();

  module.exports = new DiceRoller;

}).call(this);

//# sourceMappingURL=index.js.map
